### ISSUE TITLE
Can someone push master to crates.io please?

### ISSUE THREAD

**Issue by gilescope** [gsingh93/trace#11]
Can someone push master to crates.io please? version on master no longer compatible with latest rustc but head is. Took a little head scratching to figure out that was the issue.

**Comment by gilescope** [comment]
Also I think your crate is great! Wish I'd found it earlier. Have nominated it for crate of the week:
https://users.rust-lang.org/t/crate-of-the-week/2704/360

**Comment by gsingh93** [comment]
Sorry, just saw this. Will update the crates.io version soon.

**Comment by gsingh93** [comment]
Master was broken on the latest nightly (1.26). Just fixed that and pushed to master. New version is 0.1.4.
