### ISSUE TITLE
Still alive?

### ISSUE THREAD

**Issue by HaronK** [gsingh93/trace#26]
Is this crate still alive?
I was trying to use it today but got an error:

>    Compiling trace v0.1.4
> error[E0557]: feature has been removed
>  --> /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/trace-0.1.4/src/lib.rs:1:12
>   |
> 1 | #![feature(quote, plugin_registrar, rustc_private, slice_concat_ext)]
>   |            ^^^^^ feature has been removed
> 
> error[E0463]: can't find crate for `syntax`
>  --> /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/trace-0.1.4/src/lib.rs:3:1
> 
>   |
> 3 | extern crate syntax;
>   | ^^^^^^^^^^^^^^^^^^^^ can't find crate
> 
> error: aborting due to 2 previous errors

Would it be possible to fix this issue?

**Comment by HaronK** [comment]
Interesting thing. If I clone this crate locally then it works. Looks like new version should be built and uploaded to crates.io.

**Comment by gsingh93** [comment]
Thanks, for the heads up. I'll attempt to publish a new version this week, if you don't see it feel free to ping me again.

**Comment by gsingh93** [comment]
Just published version 0.1.5, let me know if you have any issues.

**Comment by HaronK** [comment]
Cool! It works now. Thank you!

I also have a few wishes so if it would be possible to implement them I'll create an issues:
- Print also a structure/enum name if method belongs to it. Sometimes when different structures have methods with the same name it hard to distinguish them:
```
   [+] Entering Vector.length()
```
- Would it be possible to make 'Entering/Exiting' text in the output optional? Usually [+] and [-] is enough to understand if we enter or exit function:
```
   [+] Entering
   [-] Exiting
```
- I'd like to define manually an indentation text that is used for nested calls. At the moment it's a single space but I would like to use 2 spaces or even '\t':
```
  [+] Entering method1
   [+] Entering method2
```

**Comment by gsingh93** [comment]
Those are good suggestions, but I don't have time to implement them myself. Feel free to create issues anyway in case someone else wants to claim them.
